const data = {
  products: [
    {
      name: 'Inuyasha',
      slug: 'Inuyasha Figure',
      height: 15,
      category: 'Anime',
      image: '/images/f1.jpg',
      price: 150,
      countInStock: 10,
      title: 'Inuyasha',
      rating: 5,
      //numReview: 10,
      description: 'Inuyasha figure',
    },
    {
      name: 'Snuyasha',
      slug: 'Inuyasha Figure',
      height: 15,
      category: 'Anime',
      image: '/images/f1.JPG',
      price: 150,
      countInStock: 10,
      title: 'Inuyasha',
      //rating: 5,
      //numReview: 10,
      description: 'Inuyasha figure',
    },
    {
      name: 'Ynuyasha',
      slug: 'Inuyasha Figure',
      height: 15,
      category: 'Anime',
      image: '/images/f1.JPG',
      price: 150,
      countInStock: 10,
      title: 'Inuyasha',
      rating: 5,
      //numReview: 10,
      description: 'Inuyasha figure',
    },
  ],
};

export default data;
